services:
  frontend:
    build:
      context: ./frontend 
    ports:
      - "8080:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend 
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/2042Game
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=2042Game
    restart: unless-stopped

volumes:
  mongo-data: