version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3030:3030"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app